### PR TITLE
Updated README and adding new folders

### PR DESCRIPTION
**Pull request by Jeanfabra**
Hi Ingmar, I'm sending to you an updated README file. Also, I created some folders where we can work and inside one of them you can find a simple python script for data transformation :)

### CODE REVIEW

**Review by Jeanfabra — COMMENTED** [review]
ok

**Review by Grayfox9 — APPROVED** [review]
Thanks Jean. Good job!

**Review by Grayfox9 — APPROVED** [review]
Changes viewed. Thanks Jean!

**Review by Grayfox9 — CHANGES_REQUESTED** [review]
I'm trying to aprove this. Sorry Jean.

**Pull request merged**
